import Database from 'better-sqlite3';
import { dirname } from 'path';
import { config, ensureDirExists } from '../config';
import { logger } from '../logger';
import { ensureAutoGeneratedCredentials } from '../auto-credentials';

const DB_PATH = config.dbPath;
let db: Database.Database | null = null;

export function getDatabase(): Database.Database {
  if (!db) {
    ensureAutoGeneratedCredentials();
    ensureDirExists(dirname(DB_PATH));
    try {
      db = new Database(DB_PATH);
    } catch (err: any) {
      if (err?.code === 'ERR_DLOPEN_FAILED' || (err?.message || '').includes('NODE_MODULE_VERSION')) {
        const msg = [
          '',
          '═══════════════════════════════════════════════════════════════',
          '  better-sqlite3 was compiled for a different Node.js version.',
          '  Fix: pnpm rebuild better-sqlite3',
          '═══════════════════════════════════════════════════════════════',
          '',
        ].join('\n')
        logger.error(msg)
        console.error(msg)
      }
      throw err
    }

    db.pragma('journal_mode = WAL');
    db.pragma('synchronous = NORMAL');
    db.pragma('cache_size = 1000');
    db.pragma('foreign_keys = ON');
    db.pragma('busy_timeout = 5000');
  }
  return db;
}

export function closeDatabase() {
  if (db) {
    db.close();
    db = null;
  }
}

// Cleanup on process exit
process.on('exit', closeDatabase);
process.on('SIGINT', closeDatabase);
process.on('SIGTERM', closeDatabase);
